package com.digi.hibernate;
// default package
// Generated Sep 27, 2015 11:17:44 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	@Override
	public String toString() {
		return "Customer [custId=" + custId + ", custName=" + custName + ", customerOrders=" + customerOrders + "]";
	}

	private Integer custId;
	private String custName;
	private String orderName;
	private Set customerOrders = new HashSet(0);

	public Customer() {
	}

	public Customer(String orderName) {
		this.orderName = orderName;
	}

	public Customer(String custName, String orderName, Set customerOrders) {
		this.custName = custName;
		this.orderName = orderName;
		this.customerOrders = customerOrders;
	}

	public Integer getCustId() {
		return this.custId;
	}

	public void setCustId(Integer custId) {
		this.custId = custId;
	}

	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	public String getOrderName() {
		return this.orderName;
	}

	public void setOrderName(String orderName) {
		this.orderName = orderName;
	}

	public Set getCustomerOrders() {
		return this.customerOrders;
	}

	public void setCustomerOrders(Set customerOrders) {
		this.customerOrders = customerOrders;
	}

}
