package com.digi.hibernate;
// default package
// Generated Sep 27, 2015 11:17:44 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * CustomerOrder generated by hbm2java
 */
public class CustomerOrder implements java.io.Serializable {

	private Integer orderId;
	private Customer customer;
	private String orderDetailName;
	private BigDecimal orderAmount;
	private String orderDescription;

	public CustomerOrder() {
	}

	public CustomerOrder(Customer customer, String orderDetailName, BigDecimal orderAmount, String orderDescription) {
		this.customer = customer;
		this.orderDetailName = orderDetailName;
		this.orderAmount = orderAmount;
		this.orderDescription = orderDescription;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getOrderDetailName() {
		return this.orderDetailName;
	}

	public void setOrderDetailName(String orderDetailName) {
		this.orderDetailName = orderDetailName;
	}

	public BigDecimal getOrderAmount() {
		return this.orderAmount;
	}

	public void setOrderAmount(BigDecimal orderAmount) {
		this.orderAmount = orderAmount;
	}

	public String getOrderDescription() {
		return this.orderDescription;
	}

	public void setOrderDescription(String orderDescription) {
		this.orderDescription = orderDescription;
	}

}
